---
abstract: 'Bugzilla and Kanbanize sync tool'
author:
  - 'Philippe M. Chiasson <gozer@cpan.org>'
build_requires:
  Module::Signature: 0
  Socket: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132140'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Bugzilla-Kanbanize
requires:
  AppConfig: 0
  Data::Dumper: 0
  File::HomeDir: 0
  FindBin: 0
  HTTP::Request: 0
  JSON: 0
  LWP::Simple: 0
  LWP::UserAgent: 0
  List::MoreUtils: 0
  URI::Escape: 0
  lib: 0
  strict: 0
  warnings: 0
version: 0.007
